### ISSUE TITLE
jquery.ime does not work in android 4.4 webview and in browsers which has buggy keypress events

### ISSUE THREAD

**Issue by palerdot** [wikimedia/jquery.ime#374]
`Keypress` events in some android browsers and android webviews (eg 4.4 android kitkat) does not work. This android bug is detailed  here - https://code.google.com/p/android/issues/detail?id=68284

Since jquery.ime uses keypress event for input method editing, the plugin does not work on those android webviews. Need some compatibility code to make this work in browsers where keypress events are buggy.

Also, It seems `keypress` event is deprecated as per the specification - http://www.w3.org/TR/DOM-Level-3-Events/#event-type-keypress

**Comment by santhoshtr** [comment]
Closing the issues since it became obsolete after 7 years

**Comment by krishnamoorthy51** [comment]
> 

i am getting  validKeypress is not defined
ReferenceError: validKeypress is not defined
    at IME.listen (jquery.ime.js:101:1) error while using 
     if ( !validKeypress ) {

                // we know that this browser does not support keypress event
                var self = this; // save reference

                this.$element.on( 'keyup', function( e ){

                    var str = $(this).val(); 
                    var c = str.slice( -1 ); // get the last pressed key
                    var code = c.charCodeAt(0);

                    // ignore everything except character keys
                    if ( !( code >= 65 && code <= 122 ) ) {
                        return;
                    }

                    // restore the original string present before this key is pressed 
                    var orig = str.slice( 0, str.length - 1 );
                    $(this).val( orig );

                    // get the character code of the pressed key
                    var press = $.Event("keypress");
                    press.ctrlKey = false;
                    press.which = code;

                    // simulate keypress; calls 'keypress' event of jquery.ime
                    self.keypress( press );

                    e.preventDefault();

                } );

            }
what can i do  @palerdot

**Comment by palerdot** [comment]
I don't think this library is maintained or not relevant anymore ... I myself moved away from this long back ... I suggest you look for alternatives ...
